version: "3.9"
services:
  pd:
    image: pingcap/pd:latest
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://127.0.0.1:2379
      - --advertise-peer-urls=http://127.0.0.1:2380
      - --initial-cluster=pd=http://127.0.0.1:2380
      - --data-dir=/data
    network_mode: "host"

  tikv:
    image: pingcap/tikv:latest
    depends_on:
      - pd
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=127.0.0.1:20160
      - --data-dir=/data
      - --pd=127.0.0.1:2379
    network_mode: "host"

  # tifs:
  #   image: hexilee/tifs:ci
  #   depends_on:
  #     - pd
  #     - tikv
  #   devices:
  #     - "/dev/fuse:/dev/fuse"
  #   volumes:
  #     - ./mnt:/mnt/tifs:shared
  #   privileged: true
  #   entrypoint: /bin/bash
  #   command:
  #     - -c
  #     - 'sleep 10; /tifs -f tifs:pd:2379 /mnt/tifs'
