name: pjdfstest
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse-dev fuse3 libfuse3-dev build-essential
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-01
          components: rustfmt, clippy
      - name: Start TiKV
        run: |
          docker-compose up -d tikv
      - uses: actions/checkout@v2
      - name: Mount tifs
        run: |
          make release
          mkdir ./mnt
          target/release/tifs tifs:127.0.0.1:2379 ./mnt
      - uses: actions/checkout@v2
      - name: Test
        run: |
          git clone https://github.com/pjd/pjdfstest.git
          cd pjdfstest
          autoreconf -ifs
          ./configure
          make pjdfstest
          cd ../mnt
          sudo prove -rv $GITHUB_WORKSPACE/pjdfstest/tests
