name: pjdfstest
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse-dev fuse3 libfuse3-dev build-essential
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-01
          components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Build
        run: make release
      - name: Start TiKV
        run: |
          docker-compose up -d tikv
      - name: Build pjdfstest
        run: |
          git clone https://github.com/pjd/pjdfstest.git
          cd pjdfstest
          autoreconf -ifs
          ./configure
          make pjdfstest
      - uses: actions/checkout@v2
      - name: Mount tifs
        run: |
          mkdir ./mnt
          ls -lah
          chmod +x target/release/tifs
          target/release/tifs tifs:127.0.0.1:2379 ./mnt
          until stat ./mnt | grep 65536
          do
            echo "Try again"
            sleep 1
          done
      - name: Test
        run: |
          cd ./mnt
          sudo prove -rv $GITHUB_WORKSPACE/pjdfstest/tests

