on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  linux:
    name: Create Linux Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y libfuse-dev libfuse3-dev build-essential
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-01
          components: rustfmt, clippy
      - name: Build
        run: |
          make release
          tar -czvf ./tifs-linux-amd64.tar.gz install.sh ./target/release/tifs ./target/release/mount
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tifs-linux-amd64.tar.gz
  macOS:
    name: Create MacOS Release
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          brew update > /dev/null && brew install --cask osxfuse
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-01
          components: rustfmt, clippy
      - name: Build
        run: |
          make release
          tar -czvf ./tifs-darwin-amd64.tar.gz install.sh ./target/release/tifs ./target/release/mount
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tifs-darwin-amd64.tar.gz